mod

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -9,3 +9,13 @@ jobs:
     steps:
       - name: Say Hello
         run: echo "Hello, World!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed Step
+        run: |
+          echo "I will fail now"
+          exit 1
+      - name: Say Goodbye
+        run: |
+          echo "This step will be skipped if the previous step fails"
